# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 408345a4bb0854ccae53eac2ddba5392db51b4ec72f0c97a8503012b4fd7a9828a9442b5d742dffdf9b4ff25de94dada1d26e5b1ec42f31491be8cdc421a5be3

test:
  secret_key_base: 90650524c6c51233e2dd0d6d283e96183e3b092bf8dd27598d9e9bed8ae24c562d6c3052414d8efb74b3183a6d93f89ef3c74f32ef1a62200ed2dfc66697bdef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
